apiVersion: apps/v1
kind: Deployment
metadata:
  name: memodawg-frontend
  namespace: memodawg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memodawg
      tier: frontend
  template:
    metadata:
      labels:
        app: memodawg
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: pipelinedave/memodawg-frontend:0.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"